# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-07 15:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dishe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_id', models.IntegerField(default=uuid.uuid4, unique=True)),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='myuser',
            fields=[
                ('user_id', models.IntegerField(db_index=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='placed_order',
            fields=[
                ('user_id', models.IntegerField(db_index=True)),
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_time', models.DateTimeField(default=datetime.datetime(2018, 10, 7, 15, 18, 27, 895000, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='restraunts',
            fields=[
                ('restraunt_id', models.IntegerField(db_index=True, default=uuid.uuid4, primary_key=True, serialize=False)),
                ('restraunt_name', models.CharField(max_length=100)),
                ('restraunt_place', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='dishe',
            name='restraunt_id',
            field=models.ForeignKey(default=uuid.uuid4, on_delete=django.db.models.deletion.CASCADE, to='restraunts.restraunts'),
        ),
    ]
